[book]
authors = ["Elena Fuentes & Alex Liao"]
language = "en"
multilingual = false
src = "src"
title = "Final Report Semaphore Noir"

[preprocessor.katex]

[output.html]
additional-css = ["custom.css"]